2d array operations


In [102]:
import numpy as np
x=np.array([[1,2,3],[1,2,3],[1,2,3]])
y=np.array([[5,6,7],[5,6,7],[5,6,7]])


In [103]:
add=np.add(x,y)
add

array([[ 6,  8, 10],
       [ 6,  8, 10],
       [ 6,  8, 10]])

In [104]:
multi=np.multiply(x,y)
multi

array([[ 5, 12, 21],
       [ 5, 12, 21],
       [ 5, 12, 21]])

In [105]:
print(x[2,1])
print(x[:,2])

2
[3 3 3]


In [106]:
X=np.array([[1,1],[0,1]])

Y=np.array([[2,2],[2,2]]) 

Z=np.dot(X,Y) 
Z

array([[4, 4],
       [2, 2]])

In [107]:
with open("ex.txt","r") as file1: 

     FileContent=file1.read() 


print(FileContent) 

This is line A
This is line B
This is line A
This is line B



In [108]:
with open("ex.txt","w") as file1: 

       file1.write("This is line C\n") 

In [109]:
with open("ex.txt","a") as writefile: 

       writefile.write("This is line A\n") 

       writefile.write("This is line B\n") 

In [110]:
X=np.array([[1,0,1],[2,2,2]]) 

out=X[0:2,2]
out

array([1, 2])

In [111]:
multi=np.dot(x,y)
multi

array([[30, 36, 42],
       [30, 36, 42],
       [30, 36, 42]])