#array operations


In [13]:
import numpy as np

u=np.array([1,2,3])
v=np.array([4,5,6])
add=np.add(u,v)
add



array([5, 7, 9])

In [14]:
sub=np.subtract(v,u)
sub

array([3, 3, 3])

In [15]:
multi=np.multiply(u,v)
multi

array([ 4, 10, 18])

In [16]:
div=np.divide(v,u)
div

array([4. , 2.5, 2. ])